---
title: "humanize_genes"
author: "Joe Germino (joe.germino@ucsf.edu)"
date: '2023-02-21'
output: html_document
---

```{r}
genes <- read.csv(
    "../DE gens LPtoMS ILC2 Distal top 200 per_uninfected.csv",
    header=FALSE
)
LP.genes <- genes[0:200, "V1"]
MS.genes <- genes[201:396, "V1"]
```

```{r}
library("biomaRt")
human = useMart(
    "ensembl",
    dataset = "hsapiens_gene_ensembl",
    host = "https://dec2021.archive.ensembl.org/"
)
mouse = useMart(
    "ensembl",
    dataset = "mmusculus_gene_ensembl",
    host = "https://dec2021.archive.ensembl.org/"
)

# LP genes
LP.genes.V2 = getLDS(
    attributes = c("mgi_symbol"),
    filters = "mgi_symbol",
    values = LP.genes,
    mart = mouse,
    attributesL = c("hgnc_symbol"),
    martL = human,
    uniqueRows=T
)
LP.genes.human <- unique(LP.genes.V2[, 2])

# MS genes
MS.genes.V2 = getLDS(
    attributes = c("mgi_symbol"),
    filters = "mgi_symbol",
    values = MS.genes,
    mart = mouse,
    attributesL = c("hgnc_symbol"),
    martL = human,
    uniqueRows=T
)
MS.genes.human <- unique(MS.genes.V2[, 2])
```

```{r}
write.csv(LP.genes.human, "../LP_DE_genes_human.csv")
write.csv(MS.genes.human, "../MS_DE_genes_human.csv")
```

